#!/bin/sh /etc/rc.common

START=99
STOP=99

BLOCKER="/etc/mesh-blocker/blocker.sh"
PID="/var/run/mesh-blocker"

start() {
	if [ ! -f "$PID" ]; then
		$BLOCKER &
	fi
}                 
 
stop() {          
	kill -9 $(cat $PID) 2>/dev/null
	rm -f $PID
}

restart()
{
	stop
	start
}
