#!/bin/sh
# This script mustn't be existing, but the mesh_auto_open_plinks=0 does not work properly. 
# Instead of set 0 and opened link by plink_action open - it happens randomly, a station may be opened or may be not.
# Thus I am going through another way and using a maclist taken from the file /etc/config/wireless, combining it to a different file 
# and then the blocker script looks for a mac that is presented in an associated list but not presented in the list of allowed mac.
# Then it block this one.

[[ "$ACTION" != ifup ]] && exit 0;

. /lib/functions.sh
config_load "wireless"

config_get MODE $DEVICE mode
[[ "$MODE" != mesh ]] && exit 0;

config_get POLICY $DEVICE macfilter
case $POLICY in
	deny)	IW_POLICY="block";;
	allow)	IW_POLICY="open";;
	*)	rm -f /tmp/mesh_maclist_allowed; exit 0;;
esac

config_get MACLIST $DEVICE maclist
cat /dev/null > /tmp/mesh_maclist_allowed
for MAC in $MACLIST; do
	echo "$MAC" >> /tmp/mesh_maclist_allowed
done
